version: '2'
services:
    neardocs-dev-mysql:
        container_name: neardocs-dev-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/NearDocs/dev-mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=neardocs
        ports:
            - "3306:3306"
        command: mysqld --lower_case_table_names=1
